cmd_drivers/gpu/arm/mali400/mali/__malidrv_build_info.o := ./scripts/gcc-wrapper.py ./../prebuilts/gcc/linux-x86/aarch64/gcc-linaro-6.3.1-2017.05-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-gcc -Wp,-MD,drivers/gpu/arm/mali400/mali/.__malidrv_build_info.o.d  -nostdinc -isystem /work2/yujian/81-rk3326/prebuilts/gcc/linux-x86/aarch64/gcc-linaro-6.3.1-2017.05-x86_64_aarch64-linux-gnu/bin/../lib/gcc/aarch64-linux-gnu/6.3.1/include -I./arch/arm64/include -Iarch/arm64/include/generated/uapi -Iarch/arm64/include/generated  -Iinclude -I./arch/arm64/include/uapi -Iarch/arm64/include/generated/uapi -I./include/uapi -Iinclude/generated/uapi -include ./include/linux/kconfig.h -D__KERNEL__ -mlittle-endian -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -std=gnu89 -fno-PIE -mgeneral-regs-only -DCONFIG_AS_LSE=1 -fno-pic -mpc-relative-literal-loads -fno-asynchronous-unwind-tables -fno-delete-null-pointer-checks -Wno-maybe-uninitialized -Wno-frame-address -Os --param=allow-store-data-races=0 -DCC_HAVE_ASM_GOTO -Wframe-larger-than=2048 -fstack-protector-strong -Wno-unused-but-set-variable -Wno-unused-const-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -fno-var-tracking-assignments -g -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fno-merge-all-constants -fmerge-constants -fno-stack-check -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -Werror=date-time -Idrivers/gpu/arm/mali400/mali/linux/license/gpl -Idrivers/staging/android -DMALI_FAKE_PLATFORM_DEVICE=1 -DMALI_PP_SCHEDULER_FORCE_NO_JOB_OVERLAP=0 -DMALI_PP_SCHEDULER_KEEP_SUB_JOB_STARTS_ALIGNED=0 -DMALI_PP_SCHEDULER_FORCE_NO_JOB_OVERLAP_BETWEEN_APPS=0 -DMALI_STATE_TRACKING=1 -DMALI_OS_MEMORY_KERNEL_BUFFER_SIZE_IN_MB=16 -DUSING_GPU_UTILIZATION=1 -DMALI_ENABLE_CPU_CYCLES=0 -DMALI_UPPER_HALF_SCHEDULING -Idrivers/gpu/arm/mali400/mali -Idrivers/gpu/arm/mali400/mali/include -Idrivers/gpu/arm/mali400/mali/common -Idrivers/gpu/arm/mali400/mali/linux -Idrivers/gpu/arm/mali400/mali/platform -Wno-date-time -DSVN_REV_STRING=\"-a42bbab\"    -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(__malidrv_build_info)"  -D"KBUILD_MODNAME=KBUILD_STR(mali)" -c -o drivers/gpu/arm/mali400/mali/.tmp___malidrv_build_info.o drivers/gpu/arm/mali400/mali/__malidrv_build_info.c

source_drivers/gpu/arm/mali400/mali/__malidrv_build_info.o := drivers/gpu/arm/mali400/mali/__malidrv_build_info.c

deps_drivers/gpu/arm/mali400/mali/__malidrv_build_info.o := \

drivers/gpu/arm/mali400/mali/__malidrv_build_info.o: $(deps_drivers/gpu/arm/mali400/mali/__malidrv_build_info.o)

$(deps_drivers/gpu/arm/mali400/mali/__malidrv_build_info.o):
