cmd_drivers/gpu/arm/bifrost/mali_kbase_strings.o := ./scripts/gcc-wrapper.py ./../prebuilts/gcc/linux-x86/aarch64/gcc-linaro-6.3.1-2017.05-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-gcc -Wp,-MD,drivers/gpu/arm/bifrost/.mali_kbase_strings.o.d  -nostdinc -isystem /work2/yujian/81-rk3326/prebuilts/gcc/linux-x86/aarch64/gcc-linaro-6.3.1-2017.05-x86_64_aarch64-linux-gnu/bin/../lib/gcc/aarch64-linux-gnu/6.3.1/include -I./arch/arm64/include -Iarch/arm64/include/generated/uapi -Iarch/arm64/include/generated  -Iinclude -I./arch/arm64/include/uapi -Iarch/arm64/include/generated/uapi -I./include/uapi -Iinclude/generated/uapi -include ./include/linux/kconfig.h -D__KERNEL__ -mlittle-endian -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -std=gnu89 -fno-PIE -mgeneral-regs-only -DCONFIG_AS_LSE=1 -fno-pic -mpc-relative-literal-loads -fno-asynchronous-unwind-tables -fno-delete-null-pointer-checks -Wno-maybe-uninitialized -Wno-frame-address -Os --param=allow-store-data-races=0 -DCC_HAVE_ASM_GOTO -Wframe-larger-than=2048 -fstack-protector-strong -Wno-unused-but-set-variable -Wno-unused-const-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -fno-var-tracking-assignments -g -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fno-merge-all-constants -fmerge-constants -fno-stack-check -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -Werror=date-time -DMALI_CUSTOMER_RELEASE=1 -DMALI_KERNEL_TEST_API=0 -DMALI_UNIT_TEST=0 -DMALI_ERROR_INJECT_ON=0 -DMALI_MOCK_TEST=0 -DMALI_COVERAGE=0 -DMALI_RELEASE_NAME=\""r11p0-01rel0"\" -DMALI_GCC_WORKAROUND_MIDCOM_4598=0 -DMALI_KBASE_PLATFORM_PATH=../../drivers/gpu/arm/bifrost/platform/"rk" -I./drivers/staging/android -Idrivers/gpu/arm/bifrost -Idrivers/gpu/arm/bifrost/platform_dummy -I -Idrivers/gpu/arm/bifrost/../../../base -I./include/linux -Idrivers/gpu/arm/bifrost/backend/gpu -DMALI_CUSTOMER_RELEASE=1 -DMALI_KERNEL_TEST_API=0 -DMALI_UNIT_TEST=0 -DMALI_ERROR_INJECT_ON=0 -DMALI_MOCK_TEST=0 -DMALI_COVERAGE=0 -DMALI_RELEASE_NAME=\""r11p0-01rel0"\" -DMALI_GCC_WORKAROUND_MIDCOM_4598=0 -DMALI_KBASE_PLATFORM_PATH=../../drivers/gpu/arm/bifrost/platform/"rk" -I./drivers/staging/android -Idrivers/gpu/arm/bifrost -Idrivers/gpu/arm/bifrost/platform_dummy -Idrivers/gpu/arm/bifrost/../../../base -I./include/linux -Idrivers/gpu/arm/bifrost -Idrivers/gpu/arm/bifrost/platform/rk -Idrivers/gpu/arm/bifrost/backend/gpu    -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(mali_kbase_strings)"  -D"KBUILD_MODNAME=KBUILD_STR(bifrost_kbase)" -c -o drivers/gpu/arm/bifrost/.tmp_mali_kbase_strings.o drivers/gpu/arm/bifrost/mali_kbase_strings.c

source_drivers/gpu/arm/bifrost/mali_kbase_strings.o := drivers/gpu/arm/bifrost/mali_kbase_strings.c

deps_drivers/gpu/arm/bifrost/mali_kbase_strings.o := \
  drivers/gpu/arm/bifrost/mali_kbase_strings.h \

drivers/gpu/arm/bifrost/mali_kbase_strings.o: $(deps_drivers/gpu/arm/bifrost/mali_kbase_strings.o)

$(deps_drivers/gpu/arm/bifrost/mali_kbase_strings.o):
